collections:
  - name: community.general
    version: ">=8.2.0"
  - name: containers.podman
roles:
  - name: gwerlas.system
    scm: git
    src: https://gitlab.com/yoanncolin/ansible/roles/system.git
    version: 0.16.1
