---
- name: Mimic Docker and DockerHub
  hosts: all
  roles:
    - role: gwerlas.podman
      vars:
        podman_mimic_docker: true
        podman_registries_config:
          unqualified-search-registries:
            - docker.io
