---
- name: Config
  become: true
  block:
    - name: Config - Kernel
      when: sysctl is defined
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop: "{{ sysctl }}"

    - name: Config - Directory
      ansible.builtin.file:
        path: /etc/containers/
        state: directory
        mode: "0755"

    - name: Config - Containers
      when:
        - default_containers_config is defined or podman_containers_config is defined
      ansible.builtin.template:
        src: containers.conf.j2
        dest: /etc/containers/containers.conf
        mode: "0644"

    - name: Config - Registries
      when: |
        default_registries_config is defined or
        podman_registries_config is defined or
        podman_mimic_docker
      ansible.builtin.template:
        src: registries.conf.j2
        dest: /etc/containers/registries.conf
        mode: "0644"

    - name: Config - Storage
      when:
        - podman_storage_defaults is defined or podman_storage_config is defined
      ansible.builtin.template:
        src: storage.conf.j2
        dest: /etc/containers/storage.conf
        mode: "0644"

    - name: Config - Libpod
      when:
        - podman_libpod_defaults is defined or podman_libpod_config is defined
      ansible.builtin.template:
        src: libpod.conf.j2
        dest: /etc/containers/libpod.conf
        mode: "0644"
