---
- name: Containers config dir
  become: true
  ansible.builtin.file:
    path: /etc/containers/
    state: directory
    mode: 0755

- name: Containers configuration
  when:
    - podman_containers_defaults is defined or podman_containers_config is defined
  become: true
  ansible.builtin.template:
    src: containers.conf.j2
    dest: /etc/containers/containers.conf
    mode: 0644

- name: Registries configuration
  when:
    - podman_registries_defaults is defined or podman_registries_config is defined
  become: true
  ansible.builtin.template:
    src: registries.conf.j2
    dest: /etc/containers/registries.conf
    mode: 0644

- name: Storage configuration
  when:
    - podman_storage_defaults is defined or podman_storage_config is defined
  become: true
  ansible.builtin.template:
    src: storage.conf.j2
    dest: /etc/containers/storage.conf
    mode: 0644

- name: Libpod configuration
  when:
    - podman_libpod_defaults is defined or podman_libpod_config is defined
  become: true
  ansible.builtin.template:
    src: libpod.conf.j2
    dest: /etc/containers/libpod.conf
    mode: 0644
