---
- name: Load facts
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/facts.yml"

- name: Pre checks
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/pre-checks.yml"

- name: Packages
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/packages.yml"

- name: Configuration
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/config.yml"

- name: Rootless mode
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/rootless.yml"

- name: Services
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/services.yml"

- name: Wrappers
  when: podman_wrappers | length > 0
  tags:
    - wrappers
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/wrappers.yml"
