---
- name: Packages - Load variables
  when: podman_packages is undefined
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/facts.yml"

- name: Packages - Configuration
  vars:
    task_file: "{{ role_path }}/tasks/packages/{{ ansible_facts.pkg_mgr }}.yml"
  when: task_file is file
  ansible.builtin.include_tasks: "{{ task_file }}"

- name: Packages
  become: true
  ansible.builtin.package:
    name: "{{ podman_packages }}"
  register: result
  until: result.failed == false
  retries: "{{ podman_retries }}"
  delay: "{{ podman_delay }}"

- name: Packages - Update facts   # noqa no-handler
  when: result.changed
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/facts.yml"

# Podman has to be installed before we can link the docker command to it.
- name: Packages - Mimic Docker
  when: podman_mimic_docker | bool
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/mimic-docker.yml"
