---
- name: Packages - Load variables
  when: podman_packages_computed is undefined
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/facts.yml"

- name: Packages
  become: true
  ansible.builtin.package:
    name: "{{ podman_packages_computed }}"
  notify: Migrate podman ressources
  register: result
  until: result.failed == false
  retries: "{{ podman_retries }}"

- name: Packages - Update facts   # noqa no-handler
  when: result.changed
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/facts.yml"

- name: Packages - Symlink docker to podman
  when:
    - podman_mimic_docker
    - not 'docker' in packages
  become: true
  ansible.builtin.file:
    src: /usr/bin/podman
    dest: /usr/bin/docker
    state: link
