---
- name: Pre-checks - Conflict with Docker Engine
  when: podman_mimic_docker
  block:
    - name: Run docker --version
      ansible.builtin.command:
        cmd: docker --version
      register: result
      changed_when: false
      check_mode: false
      failed_when: false

    - name: Skip due to Docker presence
      when: result.stdout is match "Docker"
      ansible.builtin.fail:
        msg: Docker is installed

- name: Pre-checks - Portage use flags
  when: ansible_pkg_mgr == 'portage'
  become: true
  ansible.builtin.template:
    src: portage.use.j2
    dest: /etc/portage/package.use/podman
    mode: "0644"

- name: Pre-checks - Kernel modules
  become: true
  community.general.modprobe:
    name: ip_tables
    persistent: present
