---
- name: Max user namespaces
  become: true
  ansible.posix.sysctl:
    name: user.max_user_namespaces
    value: "{{ podman_max_user_namespaces }}"
  when: podman_max_user_namespaces is defined

- name: Users
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    state: present
  loop: "{{ podman_users }}"

- name: Subuid and Subgid files
  become: true
  ansible.builtin.template:
    src: subid.j2
    dest: "{{ item }}"
    mode: 0644
  with_items:
    - /etc/subuid
    - /etc/subgid

# reset_connection task does not support when conditional,
# it cannot be handled anymore
- name: Reset connection to take effect of subids changes
  ansible.builtin.meta: reset_connection
