---
- name: Rootless mode
  become: true
  block:
    - name: Rootless - Users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop: "{{ podman_users }}"

    - name: Rootless - Subuid and Subgid files
      ansible.builtin.template:
        src: subid.j2
        dest: "{{ item }}"
        mode: 0644
      loop:
        - /etc/subuid
        - /etc/subgid
      notify:
        - Migrate podman ressources

- name: Rootless - Reset connection to take effect of subids changes
  ansible.builtin.meta: reset_connection

- name: Rootless - Migrate podman system to take effect of subids changes
  ansible.builtin.meta: flush_handlers
