---
- name: Rootless - Users
  when: podman_create_missing_users
  vars:
    system_users: "{{ podman_users }}"
  ansible.builtin.import_role:
    name: gwerlas.system
    tasks_from: users

- name: Rootless - Get user entries
  ansible.builtin.getent:
    database: passwd

- name: Rootless - Containers directories
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/rootless/directories.yml"

- name: Rootless - Subuid and Subgid files
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/rootless/subids.yml"
