---
- name: Service manager check
  vars:
    rootless_containers: "{{ _podman_containers | rejectattr('run_as', 'eq', 'root') | list }}"
    enabled_rootless_containers: "{{ rootless_containers | rejectattr('enabled', 'false') | list }}"
  when:
    - enabled_rootless_containers | length > 0
    - ansible_facts.service_mgr != "systemd"
  ansible.builtin.fail:
    msg: |
      {{ ansible_facts.service_mgr | capitalize }} doesn't support user services.
      Set 'enabled: false' to your 'podman_containers' entries if You don't
      care.

      Beware that your services won't automatically start at boot time.

      If You use 'podman_containers' variable to launche runtimes, You may
      prefer to use 'podman_wrappers' instead.

- name: Get user informations
  ansible.builtin.getent:
    database: passwd

- name: Containers on Quadlet units
  when: _podman_quadlet
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/provision/containers/quadlet.yml"

- name: Containers on the units podman generates
  when: not _podman_quadlet
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/provision/containers/generated.yml"
