---
- name: User escalation
  become: "{{ 'owner' in image }}"
  become_user: "{{ image.owner | default(omit) }}"
  no_log: "{{ 'password' in image }}"
  block:
    # Due to an idempotency issue in containers.podman.podman_image, we have to get informations first...
    - name: Image info
      containers.podman.podman_image_info:
        name: "{{ image.name }}"
      register: infos

    - name: Images
      containers.podman.podman_image:
        name: "{{ image.name }}"
        password: "{{ image.password | default(omit) }}"
        username: "{{ image.username | default(omit) }}"
      register: result
      until: not result.failed
      retries: "{{ podman_retries }}"
      delay: "{{ podman_delay }}"
      # ... and compare the pulled image ID
      changed_when: |
        ((
          result.image | json_query('[-1].Id')
        ) != (
          infos.images | json_query('[-1].Id')
        ))
