---
- name: Verify role without any options
  hosts: all
  gather_facts: false
  tasks:
    - name: Hello world
      ansible.builtin.command:
        cmd: podman run hello-world
      changed_when: false
