---
- name: Prepare
  hosts: all
  vars:
    system_packages_add_by_key:
      - acl
    system_users:
      - name: vagrant
      - name: myapp
        home: /data
        create_home: false
        password_lock: true
        shell: /usr/bin/nologin
        system: true
        uid: 200
  roles:
    - gwerlas.system
