---
- name: Verify that myapp user can run a container
  hosts: all
  tasks:
    - name: Hello world
      become: true
      become_user: myapp
      containers.podman.podman_container:
        name: test
        image: hello-world
        detach: false

    - name: Futur system user
      become: true
      ansible.builtin.user:
        name: futur
        home: /srv/futur
        password_lock: true
        shell: /usr/bin/nologin
        system: true
        uid: 300

    - name: Add John Doe
      ansible.builtin.import_role:
        name: gwerlas.podman
        tasks_from: rootless

    - name: Hello world as futur user
      become: true
      become_user: futur
      containers.podman.podman_container:
        name: test
        image: hello-world
        detach: false
